---
title: "data_stat"
author: "ajing"
date: "January 2, 2016"
output: html_document
---

Cleaning and some basic operation on data
```{r}
library(data.table)
library(ggplot2)
library(reshape2)


parseDateAndOthers <- function(train_data) {
  train_data$Start_date = as.Date(train_data$Start_date, "%d-%m-%Y")
  train_data$End_date_including_extension = as.Date(train_data$End_date_including_extension, "%d-%m-%Y")

  train_data$Offer_date <- as.POSIXlt( 
    train_data$Offer_date, 
    format = ifelse( 
     grepl("M", train_data$Offer_date), 
     "%m-%d-%y %H:%M %p", 
      "%m-%d-%Y %H:%M" 
    ) 
  )
  
  train_data = subset(train_data, select = Province:Competitor_3rd_Lowest_Price_per_standard_unit)
  return(train_data)
}

train_data <- read.csv("./data/CAX_Bidding_TRAIN_Molecule_3_4_5.csv", stringsAsFactors = F)
train_data = parseDateAndOthers(train_data)

# add a column for LOE date
train_data$LOEDate = as.Date("2011-01-01", format = "%Y-%m-%d")
train_data[train_data$Molecule == "Molecule3", "LOEDate"] = as.Date("2009-01-01", format = "%Y-%m-%d")
# test whether I did the right thing
table(train_data$Molecule, train_data$LOEDate)

# add test_pre as a training data
test_pre_data  <- read.csv("./data/CAX_Bidding_TEST_Molecule_6_Pre_LOE.csv", stringsAsFactors = F)
test_pre_data = parseDateAndOthers(test_pre_data)

test_pre_data$LOEDate = as.Date("2011-01-01", format = "%Y-%m-%d")

train_data <- rbind(data.frame(train_data), data.frame(test_pre_data))

# for testing data
## join test pos and test pre
test_pos_data <- read.csv("./data/CAX_Bidding_TEST_Molecule_6_Post_LOE.csv")

test_data = parseDateAndOthers(test_pos_data)

test_data$LOEDate = as.Date("2011-01-01", format = "%Y-%m-%d")



summary(test_data)

```

```{r}
ggplot(train_data, aes(x = Winning_price_per_standard_unit, color = Molecule)) + geom_histogram()
ggplot(test_pre_data, aes(x = Winning_price_per_standard_unit, color = Molecule)) + geom_histogram()
```

```{r}
ggplot(train_data, aes(x = Start_date, y = Winning_price_per_standard_unit, color = Molecule))+ geom_line()

ggplot(train_data[Province == "Provice1" & Region == "Region1"], aes(x = Start_date, y = Winning_price_per_standard_unit, color = Molecule))+ geom_line()
```

Join with other tables
```{r}
# dealing with years
regions <- read.csv("./data/CAX_AdditionalData_Regions.csv", header = T)
columnsAAndB<-(regions[,c(2:15)])
for (i in names(columnsAAndB)) {
  regions[[i]] <-as.numeric(gsub(",","", regions[[i]]))
}
colnames(regions)[1] <- "Region"
regions_tmp <- data.table(melt(regions, id= "Region"))

library(stringr)
new_cols <- str_split_fixed(regions_tmp$variable, "_", 2)
tmp <- cbind(year = substr(new_cols[, 1], 2, 5), property = new_cols[, 2], subset(regions_tmp, select = -variable))
melt(tmp, id.var = c("Region","year"), direction = "wide") 

regions <- dcast(tmp, Region + year ~ property, value.var="value")

colnames(regions) <- paste(colnames(regions), "_R", sep = "")

molecules <- read.csv("./data/CAX_AdditionalData/CAX_AdditionalData_Molecules.csv",header = T)
molecules$Molecule <- factor(paste("Molecule", molecules$Molecule, sep = ""))
mole_data <- subset(molecules, select = Code_1:X2014_B)
molecules <- cbind(Molecule = molecules[, "Molecule"], mole_data)

# Divide molecules data to separate rows by year
molecules_tmp <- data.table(melt(molecules, id= "Molecule", measure = 7:20)) # Skip "Code_1 ~ 5", only melt yearly data
new_cols <- str_split_fixed(molecules_tmp$variable, "_", 2)
tmp <- cbind(year = substr(new_cols[, 1], 2, 5), property = new_cols[, 2], subset(molecules_tmp, select = -variable))
melt(tmp, id.var = c("Molecule","year"), direction = "wide") 
molecules_noCodes <- dcast(tmp, Molecule + year ~ property, value.var="value")
molecules_noCodes <- merge (molecules_noCodes, molecules[1:6], by = "Molecule", all.x = TRUE) #join codes from original table
molecules <- molecules_noCodes
colnames(molecules) <- paste(colnames(molecules), "_M", sep = "")

test_data$year <- substr(test_data$Offer_date,1,4)
test_data$year[test_data$year == 2015] <- 2014
train_data$year <- substr(train_data$Offer_date,1,4)
train_data$year[train_data$year == 2015] <- 2014

print(dim(train_data))
train_data <- merge(train_data, regions, by.x = c("Region", "year")
                        , by.y = c("Region_R", "year_R"),all.x = TRUE)
train_data <- merge(train_data, molecules, by.x = c("Molecule","year")
                   , by.y = c("Molecule_M","year_M"), all.x = TRUE)
print(dim(train_data))

print(dim(test_data))
test_data <- merge(test_data, regions, by.x = c("Region", "year")
                        , by.y = c("Region_R", "year_R"),all.x = TRUE)
test_data <- merge(test_data, molecules, by.x = c("Molecule","year")
                   , by.y = c("Molecule_M","year_M"), all.x = TRUE)
print(dim(test_data))
 
test_data$year <- NULL
train_data$year <- NULL
```



Build a model
```{r}
library(caret)
library(xgboost)
require(magrittr)


## convert to factor
ToFactor <- function(data_frame) {
  for (col in colnames(data_frame)) {
    if (is.character(data_frame[1, col])) {
      data_frame[[col]] = factor(data_frame[[col]])
    }
  }
  return(data_frame)
}
train_data = ToFactor(train_data)
test_data  = ToFactor(test_data)

train_table <- data.table(train_data[!is.na(train_data[, "Winning_price_per_standard_unit"]) & train_data[, "Winning_price_per_standard_unit"] < 7,])
test_table  <- data.table(test_data)

## filling the  NAN values
train_table[is.na(Competitor_2nd_Lowest_Price_per_standard_unit), Competitor_2nd_Lowest_Price_per_standard_unit := 1000]
train_table[is.na(Competitor_3rd_Lowest_Price_per_standard_unit), Competitor_3rd_Lowest_Price_per_standard_unit := 1000]

test_table[is.na(Competitor_2nd_Lowest_Price_per_standard_unit), Competitor_2nd_Lowest_Price_per_standard_unit := 1000]
test_table[is.na(Competitor_3rd_Lowest_Price_per_standard_unit), Competitor_3rd_Lowest_Price_per_standard_unit := 1000]


trainMatrix <- train_table[,lapply(.SD,as.numeric)] %>% as.matrix
testMatrix <-  test_table[,lapply(.SD,as.numeric)] %>% as.matrix


nzv <- nearZeroVar(trainMatrix)

param <- list("objective" = "reg:linear",
              "eval_metric" = "rmse")

cv.nround <- 500
cv.nfold <- 3

bst.cv = xgb.cv(param=param, data = subset(trainMatrix, select = -Winning_price_per_standard_unit), label = trainMatrix[, "Winning_price_per_standard_unit"], 
                nfold = cv.nfold, nrounds = cv.nround)

# train the real model
nround = 76
bst = xgboost(param=param, data = subset(trainMatrix, select = -Winning_price_per_standard_unit), label = trainMatrix[, "Winning_price_per_standard_unit"], nrounds=nround)

pre_result <- predict(bst, subset(testMatrix, select = -Winning_price_per_standard_unit) )

submit_format <- read.csv("./data/CAX_Bidding_SubmissionFormat.csv")
submit_format[, "Winning_price_per_standard_unit"] <- pre_result
write.csv(submit_format, quote = F, row.names = F, file = "./predict_result.csv")
```

